FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --fix-missing \
    git ffmpeg libsm6 libxext6 curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your code
COPY . .

# Just run the app. app.py's "from_pretrained" will 
# download weights into the volume if they are missing.
CMD ["python3", "app.py"]